import { GridBox, LineEdit, HorizontalBox, Button, VerticalBox, CheckBox } from "std-widgets.slint";
import { ComboBoxScroll } from "../ComboBoxScroll.slint";
import { Logic } from "../logics.slint";
export component CategoriesPage {
    in property <[string]> the_model;
    in property <bool> ossupportbox-value;
    VerticalBox {
    HorizontalBox {
    Text {
        horizontal-alignment: center;
        vertical-alignment: center;
        text: @tr("Create a Type");
        font-size: 14px;
        height: 10%;
    }
    Text {
        horizontal-alignment: center;
        vertical-alignment: center;
        text: @tr("Remove a Type");
        font-size: 14px;
        height: 10%;
    }
}
GridBox {
    Row{
        newtypeinput := LineEdit {
            font-size: 16px;
            placeholder-text: @tr("How should your Type be called");
            padding: 8px;
            
        }
        valueofcombobox := ComboBoxScroll {
         height: 60px;
         width: 45%;
         model: the_model;
         current-value: "Select a Category to Remove";
        } 
}
Row{
    osbox := CheckBox {text: "Support OS selection";}
}
Row {
    Button {
        text: @tr("Insert into Databank");
        padding: 8px;
        max-height: 30px;
        clicked => {
            Logic.createtype(newtypeinput.text);
            if (osbox.checked){
                Logic.ossupport-value(true)
            }
            else {
                Logic.ossupport-value(false)
            }

        }
    }
    Button {
        max-height: 30px;
        text: @tr("Remove");
        clicked => {
            Logic.cabavalueofcombobox(valueofcombobox.current-value);
            valueofcombobox.current-value = "Select a Category to Remove";
        }
    } 
 }
}
}
}