import { RecordPage } from "record_page.slint";
import { RequestPage } from "request_page.slint";
import { StatisticsPage } from "statistics_page.slint";
import { AnalyzesPage } from "analyzes_page.slint";
import { CategoriesPage } from "categories_page.slint";
import { SettingsPage } from "settings_page.slint";
import { AboutPage } from "about_page.slint";

export { RecordPage, RequestPage, StatisticsPage, AnalyzesPage, CategoriesPage, SettingsPage, AboutPage }

