import {StandardTableView, HorizontalBox, GroupBox} from "std-widgets.slint";

export component RequestPage inherits Window {
    HorizontalBox {
        vertical-stretch: 1;

        GroupBox {
            title: @tr("Request-Log");
            vertical-stretch: 0;
   
    StandardTableView {

        columns: [
            { title: "ID" },
            { title: "Datum" },
            { title: "Zeit" },
            { title: "Anfragentyp" },
            { title: "Betriebssystem" },
            { title: "Kommentar" },
            { title: "Ort" },

        ];
        rows: [
            [
                { text: "Item 1" }, { text: "Item 2" },{ text: "Item 2" },{ text: "Item 2" },{ text: "Item 2" },{ text: "Item 2" },{ text: "Item 2" },
            ],
            [
                { text: "Item 1" }, { text: "Item 2" },{ text: "Item 2" },{ text: "Item 2" },{ text: "Item 2" },{ text: "Item 2" },{ text: "Item 2" },
            ],
            [
                { text: "Item 1" }, { text: "Item 2" },{ text: "Item 2" },{ text: "Item 2" },{ text: "Item 2" },{ text: "Item 2" },{ text: "Item 2" },
            ]
        ];
    }
}
    }
}