image: debian:latest

stages:
  - build

variables:
  APP_NAME: "reelix"
  RUST_VERSION: "1.78" 
before_script:
  - apt-get update -qy
  - apt-get install -y curl

build_appimage:
  stage: build
  script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain $RUST_VERSION
    - export PATH="$HOME/.cargo/bin:$PATH"
    - cargo build --release
    - cargo install cargo-deb
    - cargo deb
    - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
    - chmod +x appimagetool-x86_64.AppImage
    - ./appimagetool-x86_64.AppImage ./target/debian/$APP_NAME.deb $APP_NAME-x86_64.AppImage
  artifacts:
    paths:
      - $APP_NAME-x86_64.AppImage
  only:
    - tags
