import { Palette, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { ComboBoxScroll } from "ComboBoxScroll.slint";
import { SideBar } from "side_bar.slint";
import { RecordPage, RequestPage, StatisticsPage, AnalyzesPage, CategoriesPage, SettingsPage, AboutPage } from "pages/pages.slint";
import { Logic, ReelixPalette } from "./globale.slint";

export { Logic }


export component MainWindow inherits Window {
    in-out property <[string]> the_model;
    in-out property <bool> ossupportbox-value;
    in-out property <string> thedate;

    height: 420px;
    width: 820px;
    title: @tr("Reelix");
    icon: @image-url("../images/Reelix.png");

    HorizontalLayout {
        side-bar := SideBar {
            title: @tr("Reelix");
            model: [
                @tr("Menu" => "Record"),
                @tr("Menu" => "Request-Log"),
                @tr("Menu" => "Statistics"),
                @tr("Menu" => "Analyzes"),
                @tr("Menu" => "Manage Categories"),
                @tr("Menu" => "Settings"),
                @tr("Menu" => "About")
            ];
        }
        if(side-bar.current-item == 0) : RecordPage {the_model: the_model; thedate: thedate; ossupportbox-value: ossupportbox-value;}
        if(side-bar.current-item == 1) : RequestPage {}
        if(side-bar.current-item == 2) : StatisticsPage {}
        if(side-bar.current-item == 3) : AnalyzesPage {}
        if(side-bar.current-item == 4) : CategoriesPage {the_model: the_model;ossupportbox-value: ossupportbox-value;}
        if(side-bar.current-item == 5) : SettingsPage {}
        if(side-bar.current-item == 6) : AboutPage {}

        init => {
            if (Palette.color-scheme == ColorScheme.light) {
                ReelixPalette.night-mode = false;
            } else {
                ReelixPalette.night-mode = true;
            }
        }
    }
}