import { VerticalBox, CheckBox, Button } from "std-widgets.slint";

export component MainWindow inherits Window {
 
callback hello-value(bool);

    title: @tr("Checkbox-bool");
    width: 200px;
    height: 100px;
    VerticalBox {
        spacing: 5px;
        alignment: center;
        box:= CheckBox {
        text: "Check the checkbox";
    }
    Button {
        text: "Is the Checkbox checked?";
        clicked => {
            if (box.checked){
                hello-value(true)
            }
            else {
                hello-value(false)
            }
        }
    }
    Text {text: "Output is in the terminal";}
}
}

