import { Palette } from "std-widgets.slint";
export global Others  {
    in property <bool> widgets-enabled: true;
}
export global Logic {
    callback open-url(string);
    callback cabavalueofcombobox(string);
    callback createtype(string);
    callback ossupport-value(bool);
    callback makerecord(string);
    callback commentrequest(string);
    callback location(string);
    callback OperatingSystem(string);
}

export global ReelixPalette {
    in property <bool> night-mode: false;
    out property <color> control-background: root.night-mode ? #2c2c2c : #d0d0d0;
}
