import { VerticalBox, Palette, HorizontalBox } from "std-widgets.slint";
import { ReelixPalette } from "./globale.slint";




export RadioButton := TouchArea {
    property <bool> checked;
    property text <=> t.text;
    HorizontalLayout {
        spacing: 5px;
        VerticalLayout {
            alignment: center;
            Rectangle {
                width: 20px;
                height: 20px;
                border-width: 1.5px;
                border-color: root.has-hover ? Palette.border : transparent;
                border-radius: width / 2;
                background: root.pressed ? Palette.control-background.brighter(200%) : Palette.control-background;
                if checked : Rectangle {
                    background: root.has-hover ? Palette.control-background.brighter(10%) : Palette.control-background;
                    border-radius: width / 2;
                    width: parent.width / 2;
                    height: parent.width / 2;
                    x: parent.width / 4;
                    y: parent.width / 4;
                }
            }
        }
        t := Text {}
    }
}
